using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArconConnector.BusinessEntities
{
    public class Enum
    {
        public enum ConnectorType
        {
            None = 0,
            Exe = 1,
            WebBrowser = 2,
            RDPTerminal = 3,
            SSHTerminal = 4
        }

        public enum ServiceType
        {
            NONE = -100,
            SSHTelnet = 0,
            WindowsRDP = 1,
            MSSQLEMLocal = 2,
            SybaseQA = 3,
            MySQLQA = 4,
            TelnetROUTER = 5,
            SSHUNIX = 6,
            SSHLINUX = 7,
            DB2QA = 8,
            AIX = 9,
            IBMAS400 = 10,
            IBMAS390 = 11,
            OracleQA = 12,
            MSSQLQA = 13,
            MSSQLEMRDP = 14,
            SSHOracleSQLPlus = 15,
            DMZSSHLinux = 16,
            DMZSSHTelnet = 17,
            TelnetJuniperRouterSSG20 = 21,
            TelnetJuniperRouterJ2300 = 22,
            DMZWindowsRDP = 23,
            AppToadOracle = 31,
            AppToadDB2 = 32,
            AppSQLDeveloperOracle = 33,
            AppSmarTermTelnet = 34,
            AppSmarTermSSH2 = 35,
            AppWebBrowser = 36,
            AppUNIXGUI = 37,
            AppKVMSwitchSSH2 = 38,
            AppKVMSwitchBrowser = 39,
            AppHMCBrowser = 40,
            AppBrocadeSwitchBrowser = 41,
            AppMDSSwitchJAVAClient = 42,
            AppIBMTotalStorageProductivityCenter = 43,
            AppCiscoDeviceManager = 44,
            AppClearCaseRemoteClient = 45,
            AppIBMConsoleBrowser = 46,
            AppPortalInternalAdministrationBrowser = 47,
            AppVMwarevSphereClient = 48,
            SSHRouter = 49,
            SSHSwitch = 50,
            SSHFirewall = 51,
            TelnetSwitch = 52,
            AppMySQLAdministrator = 53,
            AppNetnumanZTEGSMBSC = 54,
            AppNetnumanZTEGSMMSC = 55,
            AppNetnumanZTEGSMMINOS = 56,
            AppNetnumanZTEGSMUGMSC = 57,
            AppGOGlobalAlcatel = 58,
            AppHuaweiHLRSMU = 59,
            AppNetnumanZTEGSMMGW = 60,
            AppNetnumanZTEGSMEMS = 61,
            AppNetnumanZTEGSMNGN = 62,
            AppNetnumanZTECDMABSC = 63,
            AppNetnumanZTECDMAMSC = 64,
            AppNetnumanZTECDMAMGW = 65,
            AppNetnumanZTECDMAGMGW = 66,
            AppNetnumanZTECDMAGMSC = 67,
            AppNetnumanZTECDMAPOMC = 68,
            AppNetnumanZTECDMAEMS = 69,
            AppCheckPoint = 70,
            AppCiscoASDM = 71,
            AppPLSQLDeveloperOracle = 72,
            AppAMDOCSCRM = 73,
            AppClarifyClient = 74,
            AppSingleView = 75,
            AppSAPLogon = 76, //From Here - No Log Method Condition [else RDPLog]
            AppIBMProventiaSiteProtector = 77,
            AppIBMDB2Client = 78,
            AppIBMDataStudio = 79,
            AppDBVisualizer = 80,
            ARCONDeskInsight = 81,
            AppIBMRationalClearQuest = 82,
            AppIBMRationalClearCase = 83,
            AppIBMSASEnterpriseGuide = 84,
            AppIBMSASDataIntegrationStudio = 85,
            AppComverseCustomerCareClient = 86,
            AppJuniperNetworksNSM = 87,
            IBMZOS = 88,
            AppMochaSoft = 89,
            AppNSCCNCMSClient = 90,
            AppOutsideView = 91,
            SSHSybaseISQL = 92,
            AppEnterpriseManagerConsoleOracle = 93,
            AppAttachmateReflection = 94,
            AppHuaweiLMTClient = 95,
            AppHuaweiiManagerI2000 = 96,
            AppHuaweiSAUPMS = 97,
            AppHuaweiOAMClient = 98,
            AppHuaweiLMTClientOMS2600 = 99,
            AppHuaweiAirbridge = 100,
            AppHuaweiiManagerN2000 = 101,
            AppTippingPointSMSClient = 102,
            AppOracleDiscoverer = 103,
            AppOracleWorkflowBuilder = 104,
            AppHuaweiiManagerU2000 = 105,
            AppHuaweiiManagerM2000 = 106,
            AppHuaweiServiceSMAP = 107,
            AppHuaweiSystemSMAP = 108,
            AppSecureShellClient = 109,
            AppSQuirreLSQLClient = 110,
            AppMobaXterm = 111,
            AppEmbarcaderoDBArtisan = 112,
            AppCitrixXenApp = 113,
            AppOracleEBS = 114,
            AppDameWare = 115,
            AppArcSightConsole = 116,
            AppdqMan = 117,
            AppNetnumenHLR = 118,
            AppNetnumenHLRAgent = 119,
            AppNetnumenHLREMS = 120,
            AppNetnumenHLRIQT = 121,
            AppSymantecProcommPlus = 122,
            AppDelliDRAC = 123,
            AppCeraMapPolyView = 124,
            AppMRWIN6530 = 125,
            AppIBMNotesLotus = 126,
            AppCiscoNetworkAssistant = 127,
            AppAvayaCMSSupervisor = 128,
            AppNTSWinCashLogistics = 129,
            AppVeeamONEMonitor = 130,
            AppCGClusterZTEMSC = 131,
            AppMySQLWorkBench = 132,
            AppSqlDbx = 133,
            AppMcafeeStoneSoft = 134,
            AppFileZilla = 135,
            AppTeraTerm = 136,
            AppAvamarDataCenter = 137,
            AppAvamarLocation = 138,
            AppSQLNavigator = 139,
            AppWinSCP = 140,
            AppPgAdminPostgreSQL = 141,
            AppMongoDbStudio3T = 142,
            AppIBMWIntegrate = 143,
            AppSQLyog = 144,
            AppIBMNetezzaAdmin = 145,
            AppAvayaSiteAdministration = 146,
            AppAginityWorkbench = 147,
            AppSQLTools = 148,
            AppMySqlDreamCoder = 149,
            AppForeScoutCounterACTAdmin = 150,
            AppAbInitioGDE = 151,
            AppIBMSASManagementConsole = 152,
            AppReflectionX = 153,
            AppSecureCRT = 154,
            AppIBMSASWorkflowStudio = 155,
            AppIBMBigFixConsole = 156,
            AppFastrackBrowser = 157,
            AppWatchGuardSystemManager = 158,
            AppTn3270 = 159,
            AppExtraEnterprise2000 = 160,
            AppTSSKeyManager = 161,
            AppOracleJDEdwardsEnterpriseOne = 162,
            AppPowerShellISE = 163,
            AppSAPHanaStudio = 164,
            AppVmwareHorizon = 165,
            AppAventailVPNConnection = 166,
            AppCitrixXenCenter = 167,
            AppSymantecEndpointProtectionManager = 168,
            AppNetHorizhonTelecomDevice = 169,
            AppSANSwitch = 170,
            AppSMCForcePoint = 171,
            AppXRDP = 172,
            AppPeopleTools = 173,
            AppBMCclient = 174,
            AppVmwareVspherePowerCli = 175,
            AppASEClient = 176,
            AppMySqlConnector = 177,
            AppOracleDataIntegrator = 178,
            AppSybaseCentral = 179,
            AppSQLAdvantage = 180,
            AppMcAfeeProxy = 181,
            AppToadForSQLServer = 182,
            AppEMCNetworker = 184,
            AppCitrixSmartLauncher = 183,
            AppMicrosoftDynamicsNAVClient = 186,
            AppRapidSQL = 185,
            AppSAPBO = 187,
            AppDellStorageManagerClient = 191
        }

        public enum CallingApplication
        {
            //[Description("ARCOSLOGINACMO")]
            ARCOSLOGINACMO,
            ARCOSSCRIPTMANAGER,
            ARCOSBIOMETRICFINGERPRINTAUTHENTICATOR,
            ARCOSUSERACCESSLOGVIEWER,
            ARCOSVNCTERMINAL,
            ARCOSAPPEXETERMINAL
        }
    }
}
